### ISSUE TITLE
Cocoapod?

### ISSUE THREAD

**Issue by ahmetb** [alexzielenski/StartAtLoginController#10]
Might be a good idea to make this easily distributable.

**Comment by ashchan** [comment]
@ahmetalpbalkan While there doesn't seem to have active update on this repo, you might be interested in creating a local podspec file as I did like this one: https://github.com/ashchan/gmail-notifr-objc/blob/master/Podspecs/StartAtLoginController.podspec

**Comment by keith** [comment]
A podspec for this already exists [in the master repo](https://github.com/CocoaPods/Specs/blob/master/Specs/StartAtLoginController/0.0.1/StartAtLoginController.podspec.json).

It would be nice if this library was updated and tagged for newer versions but in the meantime I've been using

```
pod "StartAtLoginController", :head, inhibit_warnings: true
```

In my Podfile.
