### ISSUE TITLE
Code signing issue?

### ISSUE THREAD

**Issue by jgallen23** [alexzielenski/StartAtLoginController#3]
I'm using this code in my app, but apple is rejecting it because it's not code signed.  When I enable code signing on the helper app, apple rejects it for "Invalid Provisioning Profile"

any ideas?

**Comment by yene** [comment]
No connection to the code.
Please follow the steps from the apple iOS Provisioning Portal

**Comment by jgallen23** [comment]
Yeah, it worked after I created another provision for the helper app
