### ISSUE TITLE
Undefined symbols for architecture x86_64 problem

### ISSUE THREAD

**Issue by TomLiu** [alexzielenski/StartAtLoginController#4]
Hi, thank your for your code. When I tried to use your code, I met the a problem after I add the file to my project. Do you have idea how to slove this? Thank you a lot. the error info is

   "Undefined symbols for architecture x86_64:
   "_kSMDomainUserLaunchd", referenced from:
      -[StartAtLoginController startAtLogin] in StartAtLoginController.o
   "_SMCopyAllJobDictionaries", referenced from:
      -[StartAtLoginController startAtLogin] in StartAtLoginController.o
   "_SMLoginItemSetEnabled", referenced from:
      -[StartAtLoginController setStartAtLogin:] in StartAtLoginController.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by alexzielenski** [comment]
You need to link the ServiceManagement framework in your target.

**Comment by bumper314** [comment]
Same error here after upgrading to Xcode 4.5, but I indeed have ServiceManagement in my target.
