### ISSUE TITLE
Bundle identifiers

### ISSUE THREAD

**Issue by tomtaylor** [alexzielenski/StartAtLoginController#6]
Thanks for this. Do you have any suggestions about the best way to manage the bundle identifiers for the main app and its helper? Should they be exactly the same? It might be useful to put this in the docs.

**Comment by pjv** [comment]
i had some code signing validation issues when i tried to make the helper app have the same bundle id as the main app. i got everything working and through app store validation by using a unique bundle id for the helper app.

**Comment by tomtaylor** [comment]
Thanks, so something like `com.example.App` for the main app, and `com.example.AppHelper` for the helper?

**Comment by pjv** [comment]
yeah, that's exactly what i did.

**Comment by tomtaylor** [comment]
Thanks - have you see any errors like the following, when starting the helper?

```
29/04/2012 20:12:05.222 SatelliteEyesHelper: LSOpenFromURLSpec() returned -10827 for application /Applications/Satellite Eyes.app path (null).
```

It looks like a few people have reported it on the Mac Developer forums, but no one has an obvious solution.

**Comment by pjv** [comment]
i just searched through my console for the string LSOpenFromURLSpec and it found no matches, so i can't help you with that one.

**Comment by tomtaylor** [comment]
FWIW, for anyone else finding this: I flushed my Launch Services cache using Onyx, and it works now. Argh!

**Comment by chestnutcode** [comment]
I have the same problem (LSOpenFromURLSpec returned -10827). It seems that the helper application needs the path to the executable, not the path to the bundle. In particular, I have to do something like this:

```
[[NSWorkspace sharedWorkspace] launchApplication:@"/Applications/MainApp.app/Contents/MacOS/MainApp"];
```

**Comment by HBehrens** [comment]
Have a look at [Tim Schröder's blog post](http://blog.timschroeder.net/2012/07/03/the-launch-at-login-sandbox-project/) where he describes the helper app in detail. He comes up with this code

```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
    // Check if main app is already running; if yes, do nothing and terminate helper app
    BOOL alreadyRunning = NO;
    NSArray *running = [[NSWorkspace sharedWorkspace] runningApplications];
    for (NSRunningApplication *app in running) {
        if ([[app bundleIdentifier] isEqualToString:@"com.timschroeder.LaunchAtLoginApp"]) {
            alreadyRunning = YES;
        }
    }

    if (!alreadyRunning) {
        NSString *path = [[NSBundle mainBundle] bundlePath];
        NSArray *p = [path pathComponents];
        NSMutableArray *pathComponents = [NSMutableArray arrayWithArray:p];
        [pathComponents removeLastObject];
        [pathComponents removeLastObject];
        [pathComponents removeLastObject];
        [pathComponents addObject:@"MacOS"];
        [pathComponents addObject:@"LaunchAtLoginApp"];
        NSString *newPath = [NSString pathWithComponents:pathComponents];
        [[NSWorkspace sharedWorkspace] launchApplication:newPath];
    }
    [NSApp terminate:nil];
}
```
