### ISSUE TITLE
"Entries set by this class do not appear in the Accounts Panel of System Preferences."

### ISSUE THREAD

**Issue by pkamb** [alexzielenski/StartAtLoginController#8]
Is there any way around this limitation? Is the only way for the user to "un-open-at-login" the app then to do it through the app's interface?

Seems kind of crazy that the new Apple-sanctioned sandbox-safe way to open at login doesn't show in System Preferences....

**Comment by alexzielenski** [comment]
Holy shit I never noticed this issue. For the purposes of the internet and helping someone else with this question I'll answer it. Using the ServiceManagement APIs which are recommended/required for sandboxed applications there is no way around this limitation. You can read more about this here: https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html#//apple_ref/doc/uid/10000172i-SW5-BAJJBJEG
